-- Run to have all DAX query in DAX studio
SELECT [Name], [Expression] 
FROM $SYSTEM.TMSCHEMA_MEASURES

-- Number of albums
DISTINCTCOUNT(spotify_history[album_name])

-- MinMax Albums Line Chart
VAR _MaxValue = MAXX(ALLSELECTED('Date Table'[Year]), CALCULATE(DISTINCTCOUNT(spotify_history[album_name])))

VAR _MinValue = MINX(ALLSELECTED('Date Table'[Year]), CALCULATE(DISTINCTCOUNT(spotify_history[album_name])))

VAR _CurrentValue = DISTINCTCOUNT(spotify_history[album_name])

RETURN

    IF(_CurrentValue = _MaxValue || _CurrentValue = _MinValue, _CurrentValue, BLANK())


-- LastestYear Albums
VAR _LastestYear = MAX('Date Table'[Year])

RETURN

CALCULATE(DISTINCTCOUNT(spotify_history[album_name]), 'Date Table'[Year] = _LastestYear)

-- PreviousYear Albums
VAR _LastestYear = MAX('Date Table'[Year])

VAR _PreviousYear = _LastestYear -1

RETURN

CALCULATE(DISTINCTCOUNT(spotify_history[album_name]), 'Date Table'[Year] = _PreviousYear)

-- PY and YoY Albums KPI
VAR _lastest = [LastestYear Albums]
VAR _previous = [PreviousYear Albums]

VAR _YoY = IF(NOT(ISBLANK(_previous)), DIVIDE(_lastest - _previous, _previous, 0),
        BLANK())

RETURN

IF(NOT(ISBLANK(_previous)),
    "vs PY: " & FORMAT(_previous, "#,##0") &
    "(" & FORMAT(_YoY, "0.00%") & ")",
    "No Data")

-- Max Year
MAX('Date Table'[Year])

-- No of Artists
DISTINCTCOUNT(spotify_history[artist_name])

-- MinMax Artists Line Chart
VAR _MaxValue = MAXX(ALLSELECTED('Date Table'[Year]), CALCULATE(DISTINCTCOUNT(spotify_history[artist_name])))

VAR _MinValue = MINX(ALLSELECTED('Date Table'[Year]), CALCULATE(DISTINCTCOUNT(spotify_history[artist_name])))

VAR _CurrentValue = DISTINCTCOUNT(spotify_history[artist_name])

RETURN

    IF(_CurrentValue = _MaxValue || _CurrentValue = _MinValue, _CurrentValue, BLANK())

-- LastestYear Artists
VAR _LastestYear = MAX('Date Table'[Year])

RETURN

CALCULATE(DISTINCTCOUNT(spotify_history[artist_name]), 'Date Table'[Year] = _LastestYear)

-- PreviousYear Artists
VAR _LastestYear = MAX('Date Table'[Year])

VAR _PreviousYear = _LastestYear -1

RETURN

CALCULATE(DISTINCTCOUNT(spotify_history[artist_name]), 'Date Table'[Year] = _PreviousYear)

-- PY and YoY Artists KPI
VAR _lastest = [LastestYear Artists]
VAR _previous = [PreviousYear Artists]

VAR _YoY = IF(NOT(ISBLANK(_previous)), DIVIDE(_lastest - _previous, _previous, 0),
                BLANK())

RETURN

IF(NOT(ISBLANK(_previous)),
    "vs PY: " & FORMAT(_previous, "#,##0") &
    "(" & FORMAT(_YoY, "0.00%") & ")",
    "No Data")

-- No of Tracks
DISTINCTCOUNT(spotify_history[track_name])

-- MinMax Tracks Line Chart
VAR _MaxValue = MAXX(ALLSELECTED('Date Table'[Year]), CALCULATE(DISTINCTCOUNT(spotify_history[track_name])))

VAR _MinValue = MINX(ALLSELECTED('Date Table'[Year]), CALCULATE(DISTINCTCOUNT(spotify_history[track_name])))

VAR _CurrentValue = DISTINCTCOUNT(spotify_history[track_name])

RETURN

    IF(_CurrentValue = _MaxValue || _CurrentValue = _MinValue, _CurrentValue, BLANK())

-- LastestYear Tracks
VAR _LastestYear = MAX('Date Table'[Year])

RETURN

CALCULATE(DISTINCTCOUNT(spotify_history[track_name]), 'Date Table'[Year] = _LastestYear)

-- PreviousYear Tracks
VAR _LastestYear = MAX('Date Table'[Year])

VAR _PreviousYear = _LastestYear -1

RETURN

CALCULATE(DISTINCTCOUNT(spotify_history[track_name]), 'Date Table'[Year] = _PreviousYear)

-- PY and YoY Tracks KPI
VAR _lastest = [LastestYear Tracks]
VAR _previous = [PreviousYear Tracks]

VAR _YoY = IF(NOT(ISBLANK(_previous)), DIVIDE(_lastest - _previous, _previous, 0),
                BLANK())

RETURN

IF(NOT(ISBLANK(_previous)),
    "vs PY: " & FORMAT(_previous, "#,##0") &
    "(" & FORMAT(_YoY, "0.00%") & ")",
    "No Data")

-- Avg Listening Time
AVERAGE(spotify_history[ms_played]) / 60000

-- Track Frequency
COUNTROWS(spotify_history)

-- CF Quadrant
VAR AvgTime = [Avg Listening Time] <= 'Listening Time (min)'[Listening Time Value]
VAR TrackFreq = [Track Frequency] <= 'Track Frequency (Parameter)'[Track Frequency (Parameter) Value]

VAR RESULT =
    SWITCH(
        TRUE(),
        AvgTime && TrackFreq, 1, --Low time & high freq
        NOT AvgTime && TrackFreq, 2, --High time & high freq
        NOT AvgTime && NOT TrackFreq, 3, --High time & low freq
        AvgTime && NOT TrackFreq, 4 --Low time & low freq
    )

    RETURN RESULT

-- Listening Time Value
SELECTEDVALUE('Listening Time (min)'[Listening Time (min)])

-- Track Frequency (Parameter) Value
SELECTEDVALUE('Track Frequency (Parameter)'[Track Frequency (Parameter)])
